# Generated by Django 5.1.6 on 2025-02-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('research_paper', 'Research Paper'), ('thesis', 'Thesis'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
