# Generated by Django 5.1.6 on 2025-02-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_remove_document_document_type_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('research_paper', 'Research Paper'), ('thesis', 'Thesis'), ('certificate', 'Certificate'), ('other', 'Other'), ('Report', 'Report')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
